name: NPM Publish CI

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Package to NPMJS
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          node-version: "18"
        env:
          HOST_URL: ${{ vars.HOST_URL }}
      - run: npm ci
      - run: npm run build
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public

      
      