name: 'PR code tests'
on:
  pull_request:
    paths:
      - '**.ts'
      - '**.scss'
      - '**.json'

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout project
        uses: actions/checkout@v2
      -
        name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'
      - run: npm ci
      -
        name: Cache packages
        uses: actions/cache@v2
        with:
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ hashFiles('package-lock.json') }}
          path: |
            ./node_modules
  test:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout project
        uses: actions/checkout@v2
      -
        uses: actions/cache@v2
        id: cache
        with:
          path: ./node_modules
          key: npm-${{ hashFiles('package-lock.json') }}
      -
        name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'
      - run: npm test
